---
version: "3"
services:
  db:
    image: postgres:15.3-alpine3.18
    container_name: sprinkler-system-postgres
    environment:
      POSTGRES_PASSWORD: 'password'
    volumes:
      - sprinkler-system-postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: unless-stopped
  
  # adminer:
  #   image: adminer:4.8.1
  #   container_name: adminer
  #   restart: unless-stopped
  #   ports:
  #     - 8080:8080

volumes:
  sprinkler-system-postgres-data:
